services:
  backend:
    build: ./backend
    container_name: straits-fx-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
     
    volumes:
      - ./backend:/app
    command: python run.py

  frontend:
    build: ./frontend
    container_name: straits-fx-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
